# Generated by Django 4.2.1 on 2025-03-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_stok', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='created_by',
        ),
    ]
