# Generated by Django 5.1.6 on 2025-03-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanPenawaranPengadaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=255)),
                ('jumlah_produk', models.PositiveIntegerField()),
                ('deskripsi_produk', models.TextField(blank=True, null=True)),
                ('url_foto_produk', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Diproses'), ('ditolak', 'Ditolak'), ('dikirim', 'Dikirim'), ('diterima', 'Diterima')], default='diajukan', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('harga_diajukan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
