# Generated by Django 5.1.7 on 2025-03-20 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pengajuan_penawaran_pengadaan", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PenawaranPengadaan",
            new_name="PengajuanPenawaranPengadaan",
        ),
    ]
