# Generated by Django 5.1.7 on 2025-03-24 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pengajuan_penawaran_pengadaan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pengajuanpenawaranpengadaan",
            name="tanggal_diterima_dikirim",
            field=models.DateField(default=datetime.date(2025, 3, 24)),
        ),
        migrations.AddField(
            model_name="pengajuanpenawaranpengadaan",
            name="tanggal_estimasi",
            field=models.DateField(default=datetime.date(2025, 3, 24)),
        ),
    ]
