# Generated by Django 5.1.7 on 2025-03-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penawaran_pengadaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penawaranpengadaan',
            name='harga_diajukan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='penawaranpengadaan',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Diproses'), ('ditolak', 'Ditolak'), ('dikirim', 'Dikirim'), ('diterima', 'Diterima')], default='diajukan', max_length=20),
        ),
    ]
