# Generated by Django 5.1.7 on 2025-03-20 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_stok', '0001_initial'),
        ('penawaran_pengadaan', '0002_penawaranpengadaan_harga_diajukan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='penawaranpengadaan',
            name='kategori_produk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manajemen_stok.kategori'),
        ),
        migrations.AddField(
            model_name='penawaranpengadaan',
            name='supplier_vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'vendor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
